#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Oct 27 17:35:55 CDT 2025
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 60550ca01c9543bab97319f603cc814e --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot staged_mac_func_impl xil_defaultlib.staged_mac -log elaborate.log"
xelab -wto 60550ca01c9543bab97319f603cc814e --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot staged_mac_func_impl xil_defaultlib.staged_mac -log elaborate.log

