# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/cam2022/CPRE-487_git/CPRE-4870/Project/hw/simple_interface/vivado/simple_interface/simple_interface.srcs/sources_1/bd/staged_mac_bd/ip/staged_mac_bd_piped_mac_0_0/staged_mac_bd_piped_mac_0_0.xci
# IP: The module: 'staged_mac_bd_piped_mac_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/cam2022/CPRE-487_git/CPRE-4870/Project/hw/simple_interface/vivado/simple_interface/simple_interface.srcs/sources_1/ip/floating_point_0/floating_point_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==floating_point_0 || ORIG_REF_NAME==floating_point_0} -quiet] -quiet

# XDC: /home/cam2022/CPRE-487_git/CPRE-4870/Project/hw/simple_interface/vivado/simple_interface/simple_interface.srcs/sources_1/bd/staged_mac_bd/ip/staged_mac_bd_piped_mac_0_0/staged_mac_bd_piped_mac_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'staged_mac_bd_piped_mac_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/cam2022/CPRE-487_git/CPRE-4870/Project/hw/simple_interface/vivado/simple_interface/simple_interface.srcs/sources_1/bd/staged_mac_bd/ip/staged_mac_bd_piped_mac_0_0/staged_mac_bd_piped_mac_0_0.xci
# IP: The module: 'staged_mac_bd_piped_mac_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/cam2022/CPRE-487_git/CPRE-4870/Project/hw/simple_interface/vivado/simple_interface/simple_interface.srcs/sources_1/ip/floating_point_0/floating_point_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==floating_point_0 || ORIG_REF_NAME==floating_point_0} -quiet] -quiet

# XDC: /home/cam2022/CPRE-487_git/CPRE-4870/Project/hw/simple_interface/vivado/simple_interface/simple_interface.srcs/sources_1/bd/staged_mac_bd/ip/staged_mac_bd_piped_mac_0_0/staged_mac_bd_piped_mac_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'staged_mac_bd_piped_mac_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
