#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Oct 29 15:49:54 CDT 2025
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim staged_mac_bd_wrapper_behav -key {Behavioral:sim_1:Functional:staged_mac_bd_wrapper} -tclbatch staged_mac_bd_wrapper.tcl -protoinst "protoinst_files/bd_8f44.protoinst" -protoinst "protoinst_files/staged_mac_bd.protoinst" -log simulate.log"
xsim staged_mac_bd_wrapper_behav -key {Behavioral:sim_1:Functional:staged_mac_bd_wrapper} -tclbatch staged_mac_bd_wrapper.tcl -protoinst "protoinst_files/bd_8f44.protoinst" -protoinst "protoinst_files/staged_mac_bd.protoinst" -log simulate.log

