#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Oct 27 18:06:00 CDT 2025
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto c9516fcaaa9140658c3a7605c51c9126 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot piped_mac_func_impl xil_defaultlib.piped_mac -log elaborate.log"
xelab -wto c9516fcaaa9140658c3a7605c51c9126 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot piped_mac_func_impl xil_defaultlib.piped_mac -log elaborate.log

