# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/cam2022/CPRE-487_git/CPRE-4870/Project/hw/fp32_mac/vivado/tc_piped_mac/tc_piped_mac.srcs/sources_1/ip/floating_point_0/floating_point_0.xci
# IP: The module: 'floating_point_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/cam2022/CPRE-487_git/CPRE-4870/Project/hw/fp32_mac/vivado/tc_piped_mac/tc_piped_mac.srcs/sources_1/ip/floating_point_0/floating_point_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'floating_point_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/cam2022/CPRE-487_git/CPRE-4870/Project/hw/fp32_mac/vivado/tc_piped_mac/tc_piped_mac.srcs/sources_1/ip/floating_point_0/floating_point_0.xci
# IP: The module: 'floating_point_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/cam2022/CPRE-487_git/CPRE-4870/Project/hw/fp32_mac/vivado/tc_piped_mac/tc_piped_mac.srcs/sources_1/ip/floating_point_0/floating_point_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'floating_point_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
