import json

# Define the notebook structure
notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# ViT Manual Math Verification (Python -> C++ Prep)\n",
                "\n",
                "This notebook validates the exact mathematical operations required to run a Vision Transformer.\n",
                "We will:\n",
                "1. Export ground-truth data (Weights, Input, Output) from PyTorch to binary.\n",
                "2. Re-implement the ViT \"manually\" using NumPy (simulating C++ logic).\n",
                "3. Compare the results to ensure 100% mathematical parity."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import torch\n",
                "import torch.nn as nn\n",
                "import timm\n",
                "import numpy as np\n",
                "import struct\n",
                "import os\n",
                "import math\n",
                "\n",
                "# --- Configuration (Must match your trained model) ---\n",
                "IMG_SIZE = 64\n",
                "PATCH_SIZE = 8\n",
                "EMBED_DIM = 96\n",
                "DEPTH = 8\n",
                "NUM_HEADS = 4\n",
                "NUM_CLASSES = 200\n",
                "MLP_RATIO = 2.0"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 1. Generate Binary Artifacts (The \"Ground Truth\")\n",
                "We create a random model (representing your trained network) and save everything to `.bin` files. \n",
                "This simulates the environment your C++ code will face."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "def generate_artifacts():\n",
                "    print(\"Generating binary artifacts...\")\n",
                "    \n",
                "    # 1. Initialize PyTorch Model\n",
                "    torch_model = timm.models.vision_transformer.VisionTransformer(\n",
                "        img_size=IMG_SIZE, patch_size=PATCH_SIZE, in_chans=3,\n",
                "        num_classes=NUM_CLASSES, embed_dim=EMBED_DIM, depth=DEPTH,\n",
                "        num_heads=NUM_HEADS, mlp_ratio=MLP_RATIO, qkv_bias=True,\n",
                "    )\n",
                "    torch_model.eval()\n",
                "    \n",
                "    # 2. Create Dummy Input\n",
                "    # (1 Batch, 3 Channels, 64 Height, 64 Width)\n",
                "    x = torch.randn(1, 3, IMG_SIZE, IMG_SIZE)\n",
                "    \n",
                "    # 3. Run Forward Pass (Get Ground Truth)\n",
                "    with torch.no_grad():\n",
                "        y = torch_model(x)\n",
                "        \n",
                "    # 4. Save Input to Binary\n",
                "    # NOTE: PyTorch uses NCHW. C++ usually likes HWC. \n",
                "    # For this verification, we stick to NCHW to focus on the model math.\n",
                "    with open(\"test_input.bin\", \"wb\") as f:\n",
                "        f.write(x.numpy().astype(np.float32).tobytes())\n",
                "        \n",
                "    # 5. Save Output to Binary\n",
                "    with open(\"test_output.bin\", \"wb\") as f:\n",
                "        f.write(y.numpy().astype(np.float32).tobytes())\n",
                "        \n",
                "    # 6. Save Weights to Binary (Sequential dump)\n",
                "    # We also keep a \"manifest\" list of shapes to help our manual loader know what to read\n",
                "    manifest = [] \n",
                "    with open(\"model_weights.bin\", \"wb\") as f:\n",
                "        for name, param in torch_model.named_parameters():\n",
                "            data = param.detach().numpy().astype(np.float32)\n",
                "            f.write(data.tobytes())\n",
                "            manifest.append((name, data.shape))\n",
                "            \n",
                "    print(\"Artifacts saved: test_input.bin, test_output.bin, model_weights.bin\")\n",
                "    return manifest\n",
                "\n",
                "# Run generation\n",
                "weight_manifest = generate_artifacts()"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 2. Manual Implementation (The \"C++\" Logic)\n",
                "Here we define the math functions from scratch using NumPy."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# --- Math Helpers ---\n",
                "\n",
                "def manual_layernorm(x, gamma, beta, eps=1e-5):\n",
                "    \"\"\"\n",
                "    x: [Batch, Tokens, Dim]\n",
                "    gamma, beta: [Dim]\n",
                "    \"\"\"\n",
                "    # 1. Calculate Mean & Variance per token\n",
                "    mean = np.mean(x, axis=-1, keepdims=True)\n",
                "    var = np.var(x, axis=-1, keepdims=True)\n",
                "    \n",
                "    # 2. Normalize\n",
                "    x_norm = (x - mean) / np.sqrt(var + eps)\n",
                "    \n",
                "    # 3. Scale and Shift\n",
                "    return x_norm * gamma + beta\n",
                "\n",
                "def manual_gelu(x):\n",
                "    \"\"\"\n",
                "    Exact GELU approximation used by PyTorch.\n",
                "    Formula: 0.5 * x * (1 + erf(x / sqrt(2)))\n",
                "    \"\"\"\n",
                "    # We use torch.erf here because numpy doesn't have a built-in vectorised erf by default\n",
                "    # In C++, use std::erf\n",
                "    return 0.5 * x * (1 + torch.erf(torch.tensor(x) / math.sqrt(2)).numpy())\n",
                "\n",
                "def manual_softmax(x, axis=-1):\n",
                "    \"\"\"Stable Softmax\"\"\"\n",
                "    # Subtract max for numerical stability (prevents overflow)\n",
                "    e_x = np.exp(x - np.max(x, axis=axis, keepdims=True))\n",
                "    return e_x / np.sum(e_x, axis=axis, keepdims=True)\n",
                "\n",
                "def manual_linear(x, w, b=None):\n",
                "    \"\"\"\n",
                "    x: [..., In_Dim]\n",
                "    w: [Out_Dim, In_Dim] (PyTorch format)\n",
                "    \"\"\"\n",
                "    # We transpose W because PyTorch stores it as (Out, In)\n",
                "    # Math: y = x @ W.T + b\n",
                "    res = np.dot(x, w.T)\n",
                "    if b is not None:\n",
                "        res += b\n",
                "    return res"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### The Attention Block\n",
                "This is the trickiest part to port. Pay attention to the `reshape` and `transpose` steps."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "def manual_attention(x, qkv_w, qkv_b, proj_w, proj_b, num_heads):\n",
                "    B, N, C = x.shape\n",
                "    head_dim = C // num_heads\n",
                "    scale = head_dim ** -0.5\n",
                "    \n",
                "    # 1. QKV Projection\n",
                "    # Input: [1, 65, 96] -> Output: [1, 65, 288]\n",
                "    qkv = manual_linear(x, qkv_w, qkv_b)\n",
                "    \n",
                "    # 2. Split Q, K, V\n",
                "    # Reshape: [B, N, 3, Heads, HeadDim]\n",
                "    qkv = qkv.reshape(B, N, 3, num_heads, head_dim)\n",
                "    \n",
                "    # Permute to: [3, B, Heads, N, HeadDim] \n",
                "    # This separates Q, K, V and puts Heads dimension before Sequence dimension\n",
                "    qkv = qkv.transpose(2, 0, 3, 1, 4)\n",
                "    q, k, v = qkv[0], qkv[1], qkv[2] # Each is [B, Heads, N, HeadDim]\n",
                "    \n",
                "    # 3. Attention Score (Scaled Dot Product)\n",
                "    # q: [B, H, N, D], k.T: [B, H, D, N] -> attn: [B, H, N, N]\n",
                "    # Note: simple np.matmul handles the batch/head broadcasting\n",
                "    attn_score = np.matmul(q, k.swapaxes(-2, -1)) * scale\n",
                "    attn_prob = manual_softmax(attn_score, axis=-1)\n",
                "    \n",
                "    # 4. Weighted Sum\n",
                "    # attn: [B, H, N, N] @ v: [B, H, N, D] -> [B, H, N, D]\n",
                "    out = np.matmul(attn_prob, v)\n",
                "    \n",
                "    # 5. Recombine Heads\n",
                "    # Transpose back: [B, N, H, D] -> Reshape [B, N, C]\n",
                "    out = out.transpose(0, 2, 1, 3).reshape(B, N, C)\n",
                "    \n",
                "    # 6. Final Projection\n",
                "    out = manual_linear(out, proj_w, proj_b)\n",
                "    return out"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### Loading the Weights\n",
                "We read the flat binary file and reshape arrays based on the manifest."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "def load_weights_manual(filename, manifest):\n",
                "    params = {}\n",
                "    with open(filename, \"rb\") as f:\n",
                "        # Read entire file buffer\n",
                "        buffer = f.read()\n",
                "        \n",
                "    offset = 0\n",
                "    for name, shape in manifest:\n",
                "        # Calculate size of this parameter\n",
                "        size = np.prod(shape)\n",
                "        # Slicing the buffer (4 bytes per float32)\n",
                "        byte_len = int(size * 4)\n",
                "        \n",
                "        # Read and reshape\n",
                "        raw_data = struct.unpack(f'{int(size)}f', buffer[offset : offset + byte_len])\n",
                "        arr = np.array(raw_data, dtype=np.float32).reshape(shape)\n",
                "        \n",
                "        params[name] = arr\n",
                "        offset += byte_len\n",
                "        \n",
                "    return params\n",
                "\n",
                "params = load_weights_manual(\"model_weights.bin\", weight_manifest)\n",
                "print(f\"Loaded {len(params)} parameters.\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### The Manual Forward Pass\n",
                "This function stitches it all together."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "def manual_forward_pass(x_input, params):\n",
                "    # --- 1. Patch Embedding ---\n",
                "    # PyTorch uses Conv2d, but mathematically it's just a linear projection of flattened patches.\n",
                "    \n",
                "    # Get weights\n",
                "    conv_w = params['patch_embed.proj.weight'] # [96, 3, 8, 8]\n",
                "    conv_b = params['patch_embed.proj.bias']   # [96]\n",
                "    \n",
                "    # Reshape Conv weights to Linear weights: [96, 192]\n",
                "    # We flatten [In, K, K] -> [3, 8, 8] -> 192\n",
                "    linear_embed_w = conv_w.reshape(EMBED_DIM, -1)\n",
                "    \n",
                "    # Unfold image into patches\n",
                "    # x: [1, 3, 64, 64]\n",
                "    patches = []\n",
                "    for r in range(0, IMG_SIZE, PATCH_SIZE):\n",
                "        for c in range(0, IMG_SIZE, PATCH_SIZE):\n",
                "            # Extract patch [1, 3, 8, 8]\n",
                "            patch = x_input[:, :, r:r+PATCH_SIZE, c:c+PATCH_SIZE]\n",
                "            # Flatten to [1, 192]\n",
                "            patches.append(patch.flatten())\n",
                "            \n",
                "    x_patches = np.stack(patches) # [64, 192]\n",
                "    x_patches = x_patches.reshape(1, 64, -1) # [1, 64, 192]\n",
                "    \n",
                "    # Project\n",
                "    x = manual_linear(x_patches, linear_embed_w, conv_b) # [1, 64, 96]\n",
                "    \n",
                "    # --- 2. Class Token & Positional Embedding ---\n",
                "    cls_token = params['cls_token'] # [1, 1, 96]\n",
                "    pos_embed = params['pos_embed'] # [1, 65, 96]\n",
                "    \n",
                "    # Concatenate CLS token\n",
                "    x = np.concatenate([cls_token, x], axis=1) # [1, 65, 96]\n",
                "    \n",
                "    # Add Pos Embed\n",
                "    x = x + pos_embed\n",
                "    \n",
                "    # --- 3. Transformer Blocks ---\n",
                "    for i in range(DEPTH):\n",
                "        # Keys for this block\n",
                "        base = f\"blocks.{i}.\"\n",
                "        \n",
                "        # Branch 1: Norm -> Attn\n",
                "        resid = x\n",
                "        x_norm = manual_layernorm(x, params[base + 'norm1.weight'], params[base + 'norm1.bias'])\n",
                "        \n",
                "        attn_out = manual_attention(\n",
                "            x_norm,\n",
                "            params[base + 'attn.qkv.weight'], params[base + 'attn.qkv.bias'],\n",
                "            params[base + 'attn.proj.weight'], params[base + 'attn.proj.bias'],\n",
                "            NUM_HEADS\n",
                "        )\n",
                "        x = resid + attn_out\n",
                "        \n",
                "        # Branch 2: Norm -> MLP\n",
                "        resid = x\n",
                "        x_norm = manual_layernorm(x, params[base + 'norm2.weight'], params[base + 'norm2.bias'])\n",
                "        \n",
                "        # MLP: FC1 -> GELU -> FC2\n",
                "        fc1 = manual_linear(x_norm, params[base + 'mlp.fc1.weight'], params[base + 'mlp.fc1.bias'])\n",
                "        hidden = manual_gelu(fc1)\n",
                "        fc2 = manual_linear(hidden, params[base + 'mlp.fc2.weight'], params[base + 'mlp.fc2.bias'])\n",
                "        \n",
                "        x = resid + fc2\n",
                "        \n",
                "    # --- 4. Final Head ---\n",
                "    # Norm\n",
                "    x = manual_layernorm(x, params['norm.weight'], params['norm.bias'])\n",
                "    \n",
                "    # Extract CLS token (index 0)\n",
                "    cls_out = x[:, 0] # [1, 96]\n",
                "    \n",
                "    # Classification Linear\n",
                "    logits = manual_linear(cls_out, params['head.weight'], params['head.bias'])\n",
                "    \n",
                "    return logits"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 3. Final Verification\n",
                "Compare the Manual Output vs Binary Ground Truth."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 1. Load Input Binary\n",
                "with open(\"test_input.bin\", \"rb\") as f:\n",
                "    input_data = np.frombuffer(f.read(), dtype=np.float32).reshape(1, 3, IMG_SIZE, IMG_SIZE)\n",
                "\n",
                "# 2. Run Manual Model\n",
                "manual_output = manual_forward_pass(input_data, params)\n",
                "\n",
                "# 3. Load Ground Truth Output\n",
                "with open(\"test_output.bin\", \"rb\") as f:\n",
                "    gt_output = np.frombuffer(f.read(), dtype=np.float32).reshape(1, NUM_CLASSES)\n",
                "\n",
                "# 4. Compare\n",
                "print(\"--- Comparison Results ---\")\n",
                "print(f\"Manual Output Shape: {manual_output.shape}\")\n",
                "print(f\"PyTorch Output Shape: {gt_output.shape}\")\n",
                "\n",
                "# Calculate Max Difference\n",
                "diff = np.abs(manual_output - gt_output)\n",
                "max_diff = np.max(diff)\n",
                "\n",
                "print(f\"\\nMax Absolute Difference: {max_diff:.8f}\")\n",
                "\n",
                "if max_diff < 1e-4:\n",
                "    print(\"\\n✅ SUCCESS: The manual math matches PyTorch!\")\n",
                "else:\n",
                "    print(\"\\n❌ FAILURE: Check your math logic.\")\n",
                "    \n",
                "# Show first 5 logits\n",
                "print(\"\\nFirst 5 Logits (Manual): \", manual_output[0, :5])\n",
                "print(\"First 5 Logits (PyTorch):\", gt_output[0, :5])"
            ]
        }
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "codemirror_mode": {
                "name": "ipython",
                "version": 3
            },
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbconvert_exporter": "python",
            "pygments_lexer": "ipython3",
            "version": "3.8.5"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 4
}

# Write the notebook file
filename = 'ViT_Math_Verification.ipynb'
with open(filename, 'w') as f:
    json.dump(notebook, f, indent=1)

print(f"Successfully generated {filename}.")
